### ISSUE TITLE
NameError: name 'controller' is not defined

### ISSUE THREAD

**Issue by WK-GiHu** [Holly23i/coursework#5]
@Holly23i 

>However, I am actually having an issue with this when creating a home button within `onShowFrame` as the console says `NameError: name 'controller' is not defined`. 

>So yes, I would like to be able to switch between frames and I also want to clear the `resultsPage` of all widgets upon calling displayResults.

https://github.com/Holly23i/coursework/blob/4faa2998556a1ebd7d20ccb0109547b1af32e0ce/pages.py#L440
...
https://github.com/Holly23i/coursework/blob/4faa2998556a1ebd7d20ccb0109547b1af32e0ce/pages.py#L442

Replace at Line 442 with:
```
command=lambda: self.master.showFrame(homePage))
```

Try and report back, if you get a Traceback include it.

**Comment by Holly23i** [comment]
That provides a new error: `AttributeError: 'Frame' object has no attribute 'showFrame'`

**Comment by WK-GiHu** [comment]
@Holly23i 

>`AttributeError: 'Frame' object has no attribute 'showFrame'`

OK, my bad, change to:
```
command=lambda: self.master.master.showFrame(homePage))
```

**Comment by Holly23i** [comment]
That solved it! Thanks
